[ColorThemes]
KXStudio=/usr/share/qjackctl/palette/KXStudio.conf
Wonton%20Soup=/usr/share/qjackctl/palette/Wonton Soup.conf

[GraphNodePos]
SuperCollider=@Variant(\0\0\0\x1a\xc0 \0\0\0\0\0\0\xc0(\0\0\0\0\0\0)
system%3AInput=@Variant(\0\0\0\x1a@p\0\0\0\0\0\0\xc0\x62\0\0\0\0\0\0)
system%3AOutput=@Variant(\0\0\0\x1a\xc0q\x80\0\0\0\0\0\xc0\x64\0\0\0\0\0\0)
